try {
    // Intentamos ejecutar este bloque de c칩digo
    // let sum = a + 10; // Esto provocar치 un error porque 'a' no est치 definida

    throw "Error Ocasionado con throw";

} catch (error) {
    // Si hay un error en el bloque try, se ejecuta este bloque
    console.log("Ocurri칩 un error: " + error);

} finally {
    // Este bloque siempre se ejecuta, independientemente de si hubo un error o no
    console.log("El bloque finally siempre se ejecuta.");
}
